name: river-level
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  # Add additional Conda dependencies here
  # Version lock critical packages using '=' ie:
  # - packageName=0.123
  - python=3.10
  - flake8      # Linter for style adherence
  - pytest      # Unit testing framework
  - boto3       # AWS S3 interaction
  - s3fs        # AWS S3 interaction TODO: Convert to only boto3 OR only s3fs (Issue #30)
  - pip         # Package installer for dependencies not available through Conda
  - pip:
    # Add pip packages which are not available through conda here
    # Note: to version lock a pip package, use '==' not '=' ie:
    # - packageName==0.123
    - darts==0.22   # Core Timeseries forecasting library (includes Pytorch)
    - dataretrieval # Package for fetching NWIS river level dataa
    - simplekml     # Weather location KML generation
    - pyarrow       # Parquet file creation
