ARG PYTHON_VERSION="3.8"

FROM python:${PYTHON_VERSION}-slim

ARG APP_DIR="/app"
ARG CATCHMENTS_FILE="catchments_short.json"

RUN mkdir -p ${APP_DIR}

COPY src ${APP_DIR}/src
COPY data/${CATCHMENTS_FILE} ${APP_DIR}/data/${CATCHMENTS_FILE}
COPY pyproject.toml ${APP_DIR}/pyproject.toml
COPY containers/collection/lambda/requirements.txt ${APP_DIR}/requirements.txt
COPY containers/collection/lambda/app.py ${APP_DIR}/

RUN pip3 install --no-cache-dir torch --extra-index-url https://download.pytorch.org/whl/cpu && \
    pip3 install --no-cache-dir -r ${APP_DIR}/requirements.txt && \
    pip install ${APP_DIR} && \
    pip3 install --no-cache-dir awslambdaric

WORKDIR ${APP_DIR}

COPY containers/collection/lambda/entry.sh /

RUN chmod 755 /entry.sh
ENTRYPOINT [ "/entry.sh" ]
CMD [ "app.handler" ]
